# Network interface
interface=ens18
bind-interfaces

# DHCP pool
dhcp-range=10.10.0.100,10.10.0.250,255.255.255.0,12h

# Default gateway
dhcp-option=3,10.10.0.1

# DNS servers
dhcp-option=6,8.8.8.8,1.1.1.1

# Don't provide DNS itself
port=0

# DHCP logging
log-dhcp